version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: ilovesushi_db
    restart: always
    environment:
      POSTGRES_USER: ilovesushi_user
      POSTGRES_PASSWORD: ilovesushi_pass
      POSTGRES_DB: ilovesushi_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
